### ISSUE TITLE
PersistentId kısmı her zaman null gidiyor

### ISSUE THREAD

**Issue by hkulekci** [soupmix/cache-redis#2]
PersistentId persistent edilen connection için bir alias gibi bir şey vermek için kullanılıyor sanırım ancak her zaman `null` gidiyor şu anda. Config üzerinden gönderilmediğinde acaba library kendisi mi bir değer atasa?

@mkorkmaz

**Comment by mkorkmaz** [comment]
@hkulekci persistent'ı true yazan, onu da yazmasını gerektiğini bilmesi gerekir diye düşünüyorum. O zaman sanırım dokümantasyonda bunu belirtmemiz gerekir. Aslına bakarsan connection kısmını library'den çıkarıp constructor'da handler inject edilse daha mı iyi olur, onu düşünüyorum. Bu konudaki düşüncen nedir, connection'ı library mi handle etmelidir?

**Comment by hkulekci** [comment]
İki türlü olabilir aslında. Birincisi seninde söylediğin gibi handler dependency olarak verilir. Diğeri ise  Configuration nesnesi dependency olarak girer. Constructor'da biz kontrol ederiz eğer array geldiyse COnfiguration nesnesini factory ederiz. Böylelikle bir şey set edildiğinde başka bir şeyin değiştirilmesi gereken durumlar bu configuration nesnesi içerisinde kontrol edilebilir. Buradaki logic oraya gömülebilir yani. Bende bunun için bir pr hazırlayayım diye düşünmüştüm. Bu durumda git gide light olmaktan çıkıyor tabikide.

**Comment by mkorkmaz** [comment]
@hkulekci Connection handler'ı constructor'da inject edelim bence, kod da temiz ve daha kolay anlaşılır olur. O şekilde ilerleyeceğim mutabık isek?

**Comment by mkorkmaz** [comment]
I close this issue since Redis connection injected
